services:
  vms_node_app:
    build: .
    container_name: vms_node_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7
    container_name: vms_mongodb
    command: ["mongod", "--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: nest4us_volunteers
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
